### ISSUE TITLE
Problem when compiling CodeBlocks with 10.2

### ISSUE THREAD

**Issue by gerard-durand** [brechtsanders/winlibs_mingw#46]
I compile generally the last svn version CodeBlocks myself. No problems until 10.2 version release 5. Since release 6, 6b or 7, I have problems. Compilation works as expected (no errors, a few warnings but not new ones), but it's when I execute CodeBlocks that I have problems : CodeBlocks crash when I try to Compile, Compile and Run, or Rebuild a C++ software (with the button at the top or with the menus). It seems that this is due to an incompatibility with the new binutils 2.36. If I replace in your release 7 by binutils 2.35.1 (found in release 5), C::B compiles again without crash. I don't know if it's a bug in binutils or in CodeBlocks itself. For information, it's also the case with the last Msys2 updates/Downloads, and there also, C::B compiles again when I replace Binutils by the previous version. I have seen that there was modifications in ar.exe, but substituting only this executable is not sufficient.
With my own software, using wxWidgets, I have not met equivalent problems.

**Comment by brechtsanders** [comment]
There are some issues in binutils 2.36.1, especially when building debug versions. Building stripped binaries (without debug info) may help.
But release 8 which I published yesterday had some patches applied to binutils (see also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98860 ).
So please check if release 8 fixes your problem.

**Comment by gerard-durand** [comment]
I tried your release 8 but it didn't change the problem. Sorry. I build generally with the -s option, or explicitly use strip.exe (for example when building wxwidgets).
Just to be sure, I'm trying to rebuild wxWidgets 3.1.4 with your release 8, just to see if it changes something...
I also tried your snapshot build with gcc 11, but the problem is still there.

**Comment by gerard-durand** [comment]
OK, I have found that in codeblocks there was a problem in filent.c. They declare a FINDTYPE which in fact, in MinGW64, should be a long long integer, but is only set as a long. They use a macro _M_IA64 which is not defined in gcc. The surprising thing, is that it's not defined also in older gcc, but there was no problems until now. May be an optimization in recent gcc, but definitely, I think it's a codeblocks problem. I have proposed a patch to use _WIN64 or better intptr_t instead of FINDTYPE. Patch not still approved, but wait and see ...
